---
services:
  redis:
    image: redis:latest
    networks:
      - frontend
  
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - backend

  voting-app:
    build: ./vote
    networks:
      - frontend
    ports: 
      - "81:80"
  
  result-app: 
    build: ./result
    networks:
     - backend
    ports: 
      - "82:80"
  
  worker:
    build: ./worker
    networks:
      - frontend
      - backend 
       
networks:
  frontend: {}
  backend: {}