---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: result-app
spec:
  type: LoadBalancer
  selector:
    app: result-app
  ports: 
    - protocol: TCP
      port: 82
      targetPort: 80
