---
apiVersion: v1
kind: Service
metadata: 
  name: voting-app-service
  labels:
    app: voting-app
spec:
  type: LoadBalancer
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80  